### ISSUE TITLE
[bug] Submitting a username change errors out with unexpected invalid_type error

### ISSUE THREAD

**Issue by ajhalili2006** [dreadhalor/hermitcraft-horns#10]
## About this bug

I am trying to change my username from `turtle-tamer` to match my GitHub and Gmail username, but the API errored out as a bad request with the following reason on `error.json.message` key.

```json
[
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "undefined",
    "path": [],
    "message": "Required"
  }
]
```

## Reproduction / HAR Logs

**Steps**:

1. Sign in as usual
2. Go to profile and change default username generated on signup with desired username.
3. DevTools console should fire up errors regarding the request with the following errors:

```log
api/trpc/validateUsername?input={%22username%22:%22ajhalili2006%22}:1 

Failed to load resource: the server responded with a status of 400 ()

page-fce77f0ff075398f.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'data')
    at page-fce77f0ff075398f.js:1:3214
    at async x (page-fce77f0ff075398f.js:1:3084)
    at async 1905-f761a4968a84300e.js:5:18897
```

**HAR Logs**[^1]: https://gist.github.com/ajhalili2006/79cd29d0bee741fdd892332a829f5cc3#file-redacted_hc-horns-bug-202406140014-har

[^1]: These are sanitized using [Cloudflare's HAR File Sanitizer](https://har-sanitizer.pages.dev/) to avoid stealing session cookies/tokens accidentally leaked via these files.

## Additional info

* **Browser version**: Chrome 125.0.6422.141
* **OS**: Linux 6.8.11-300.fc40.x86_64 amd64 / Fedora Desktop 40
  * **Desktop environment**: KDE Plasma 6.0.5 on Wayland / KDE Frameworks 6.2.0 / Qt 6.7.1
* **User ID**: `user_2gccKVZ5jfJCwiLt3bYzeS2dRVw`

**Comment by dreadhalor** [comment]
Thanks for bringing this to my attention! I'm pushing out a bug fix for this right now.
